// src/engine/index.js — one import surface for the UI layer.
export {
  buildContext,
  mergeSettings,
  activePlayers,
  activeCount,
  playerOf,
  rosterById,
  rosteredIds,
  rosPoints,
  resolveMyRosterId,
  slotEligibility,
  seasonShape,
  resolveSlots,
  projectionPoints,
  scoringMultipliers,
  resolveNow,
  FAAB_WAIVER_TYPE,
  DEFAULT_WAIVER_CLEAR_DAYS,
  DEFAULT_WAIVER_BUDGET,
  SLOT_ELIGIBILITY,
  BENCH_SLOTS,
  QB_SLOTS,
} from "./context.js";

export {
  curveFit,
  curveValue,
  marketValue,
  waiverReplacement,
  surplus,
  sideValue,
  scaleFactors,
  rosRanks,
  rosBaselines,
  injuryDiscount,
  rosterPctScale,
  tableFor,
  tableRows,
  tableCandidates,
  roleKind,
  REFERENCE_SOURCE,
  CURVE_SOURCE,
  ROLE_TABLES,
  BC_TIER_VARIANTS,
} from "./values.js";

export {
  bestLineup,
  seasonLineup,
  backfill,
  backfillPositions,
  freeAgentPoolByPos,
  slotDemand,
  weekPoints,
  weekVector,
  isBye,
  WEEK_ZERO_STATUSES,
} from "./lineup.js";

export {
  evaluateTrade,
  finalizeExplanation,
  cheapestDroppable,
  acceptanceTier,
  edgeBand,
  edgePct,
  cachedSeasonLineup,
  verdictLabel,
  renderVerdictLabel,
  VERDICT_LABELS,
  EDGE_BANDS,
  LINEUP_OVERRIDE_PTS,
  VETO_EDGE,
  ACCEPT_EDGE,
  ACCEPT_DELTA,
} from "./trade.js";

export {
  findTrades,
  findLeagueTrades,
  tradePool,
  positionalSurplus,
  MAX_CANDIDATES,
  DEFAULT_SHAPES,
} from "./finder.js";

export {
  freeAgentPool,
  waiverStatus,
  findFreeAgents,
  gradeTransaction,
  suggestedBid,
  trendCount,
  alternativesAt,
  currentStarters,
  dropCandidates,
  protectedBySurplus,
  DAY_MS,
  CANDIDATES_PER_POS,
  MAX_FA_CANDIDATES,
  PROTECTED_BY_SURPLUS,
  MAX_BID_SHARE,
  BID_GAIN_SCALE,
  BID_PHASE_FLOOR,
  BID_AGGRESSIVE_MULT,
  ALT_BAND_PER_WEEK,
} from "./waiver.js";

export {
  explain,
  sideNames,
  defaultNames,
  resolveNames,
  voice,
  flagText,
  fmt0,
  fmt1,
  nameOf,
  namesOf,
  displayTier,
  acceptancePhrase,
  MAX_MEANINGFUL_TIER,
} from "./explain.js";
